plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kaltone.x7kanbantv'
    compileSdk 35

    defaultConfig {
        applicationId 'com.kaltone.x7kanbantv'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
